### ISSUE TITLE
Talk iOs crashes on instant 

### ISSUE THREAD

**Issue by FSDirk** [nextcloud/talk-ios#425] opened 2020-11-25 16:50 UTC
Hey

App crashes right away. 
iOS 14.2.1 iPhone 12 Pro 
Talk 10.0.3
Multiple users with same issue. 

Regardes

**Comment by Ivansss** [comment] 2020-11-25 16:58
Hi @FSDirk 

What version of the Talk iOS app are you using?

**Comment by FSDirk** [comment] 2020-11-25 17:15
Vertraulicher Inhalt - Feuer Software GmbH

Latest. 10.1.0 before that worked fine.

**Comment by JohnyDoeLP** [comment] 2020-11-25 17:20
Have the same problem,the app closes immediately after starting IOS 14.2 NC Talk 10.1.0
Crashlog 
[NextcloudTalk-2020-11-25-175047.txt](https://github.com/nextcloud/talk-ios/files/5598261/NextcloudTalk-2020-11-25-175047.txt)

**Comment by Ivansss** [comment] 2020-11-25 18:52
Have you tried with a fresh installation of the app @FSDirk @JohnyDoeLP ?
We can discard a problem with your Nextcloud setup if there are no users configured in the app.

**Comment by FSDirk** [comment] 2020-11-25 18:58
Fresh installation seems to work so far -> No real solution, I now need to inform over 100 clients...

**Comment by Ivansss** [comment] 2020-11-25 19:16
Definitely not a real solution. Just trying to identify the issue since I can't reproduce this issue in devices that have been updated or new installations. 🤷🏻‍♂️

Were you able to log in successfully to your nextcloud instance after fresh installation?
Did you update the app from 10.0.1?

**Comment by FSDirk** [comment] 2020-11-25 19:18
App is still 10.0.1 no update available. 
No problem on login. Works fine after re install.

**Comment by Ivansss** [comment] 2020-11-25 19:29
> App is still 10.0.1 no update available.

Do you mean the Talk web app or the iOS app?

**Comment by FSDirk** [comment] 2020-11-25 19:31
IOS! 

Talk is 10.0.3 as written above.

**Comment by Ivansss** [comment] 2020-11-25 19:38
You also wrote above this:

> Latest. 10.1.0 before that worked fine.

And then you are saying:

> App is still 10.0.1 no update available.

Sorry for being confused. But I still don't get how you updated your iOS app to 10.1.0 and then after a fresh installation from the App Store you get 10.0.1  and no available updates 🤷🏻‍♂️

**Comment by FSDirk** [comment] 2020-11-25 19:41
Okay... clarification: 
iOS-Version 14.2.1 (Latest version) 
Nextcloud Talk iOS 10.1.0 (Latest version)
Nextcloud Talk - "Server" App 10.0.3 (Latest Version) 

All Versions are the latest stable versions.

**Comment by Ivansss** [comment] 2020-11-25 19:45
> App is still 10.0.1 no update available.

Okay... so this was a typo ^

**Comment by SystemKeeper** [comment] 2020-11-25 19:51
@FSDirk Is there anything "special" about your device or your setup? We upgraded multiple devices today from 10.0.1 to 10.1.0 and all worked fine. iPhone, iPad, iOS 14.2, iOS 13.7, iOS 12.4. 
The crash report from @JohnyDoeLP indicates he's using 14.2, so it shouldn't be related to 14.2.1.

Any restriction, accessibility, supervision, permissions etc. ? One NC account, multiple NC accounts?

**Comment by JohnyDoeLP** [comment] 2020-11-25 19:55
> 
> 
> Have you tried with a fresh installation of the app @FSDirk @JohnyDoeLP ?
> We can discard a problem with your Nextcloud setup if there are no users configured in the app.

Have once, the APP newly installed, works wonderfully :) 
Is the red header new in the APP. 
I had hoped that my crash log could help.

**Comment by FSDirk** [comment] 2020-11-25 19:57
Our Cloud has over 100 users.. multiple have issues as described but not all of the iPhone users. 
Nothing comes directly to mind. 
We might share some media from group folders?

**Comment by SystemKeeper** [comment] 2020-11-25 19:57
> Have once, the APP newly installed, works wonderfully :)

Cool 👍 

> Is the red header new in the APP.

In a way yes - 10.1.0 supports server theming: https://github.com/nextcloud/talk-ios/pull/388 

> I had hoped that my crash log could help.

Sadly we were unable to track down the cause. We can't replicate it in any way.

**Comment by SystemKeeper** [comment] 2020-11-25 19:58
> We might share some media from group folders?

Hm, but if that's a problem, reinstallation shouldn't solve the issue I guess.

**Comment by SystemKeeper** [comment] 2020-11-25 20:11
Talking about theming... @FSDirk Are you using the theming-app / changed the theming on server? (not using default NC blue?)

**Comment by SystemKeeper** [comment] 2020-11-25 20:30
I think we found the problem. When the theming-app is disabled server-side, the app crashes immediatlely without even trying to show the UI. Maybe @FSDirk could confirm that the theming-app is disabled in your case?

@JohnyDoeLP Was the themeing-app disabled in the past on your install?

**Comment by FSDirk** [comment] 2020-11-25 20:32
Theming app has active on all the time... maybe off for a little while during update from 19 to 20. but issue had been there before...

**Comment by JohnyDoeLP** [comment] 2020-11-25 20:43
> 
> @JohnyDoeLP Was the themeing-app disabled in the past on your install?

Oh I don't know, I would have to ask our system administrator, I used to have the blue header :D

**Comment by gladonias** [comment] 2020-11-27 12:59
I'm having the same problem, app v10.1.0 crashes instantly on iPhone and iPad running the latest versions of iOS/iPadOS.

**Comment by SystemKeeper** [comment] 2020-11-27 13:02
A new version with bugfixes is currently reviewed by Apple and should be available shortly.

**Comment by osm-frasch** [comment] 2020-11-27 15:37
The same issue here. I have already asked today in the Nextcloud Support Forum about (see here: https://t1p.de/rgpe)
A new installation of Nextcloud-Talk on the iPhone fixes the error. The app no longer crashes. Text chat works. But the video chat still doesn't work. Before the system update to version 14.2. everything worked fine.

**Comment by osm-frasch** [comment] 2020-11-27 15:39
> A new version with bugfixes is currently reviewed by Apple and should be available shortly.

Sorry... I missed that.

**Comment by SystemKeeper** [comment] 2020-11-27 15:50
@osm-frasch Just to be sure, video calls worked fine for you before iOS 14.2 or before talk-iOS 10.1? Can you please open a new ticket and provide information about your environment and the error / problem you’re encountering ?

**Comment by osm-frasch** [comment] 2020-11-27 15:57
Yes, video calls worked fine before Update to  iOS 14.2. 
It was an iPhone XR. Netcloud-Talk App was been the latest Version. 

After this Update the App chrashes. We reinstalled Nextcloud-Talk App. Now the app worked again. But the video calls did not work anymore.

**Comment by Ivansss** [comment] 2020-11-27 16:23
Hi @osm-frasch :)

Could you please open a new issue with some more information about your problems with video calls?
Nextcloud server version
Nextcloud Talk version
Steps to reproduce your issue
...

This way we leave this issue for the original problem (app crash) and we can continue the discussion about your video calls problems on the new issue.

**Comment by osm-frasch** [comment] 2020-11-27 18:25
Yes i will do later . At the moment i bring the kids in bed

27.11.2020 17:23:35 Ivan Sein <notifications@github.com>:

**Comment by marekspacirek** [comment] 2020-11-28 17:07
All my iOS apps also started crashing right after launch. The problem was in the Theming application. After I enabled Theming and reinstalled the application on all iOS devices, it works.

**Comment by Ivansss** [comment] 2020-12-01 08:32
There were 2 possible issues that made the app v10.1 and v10.1.1 crash:
- Database migration process.
- Theming app disabled in the server. (This was fixed in v10.1.1)

Both issues are fixed in version 10.1.2.
Sorry for the inconvenience!

**Closed as completed by Ivansss** 2020-12-01 08:32 UTC
Labels: bug
