### ISSUE TITLE
iOS app multiple accounts

### ISSUE THREAD

**Issue by lmamane** [nextcloud/talk-ios#262] opened 2019-10-31 20:40 UTC
It seems the iOS app doesn't support multiple accounts, which the "Files" Nextcloud app does,

**Comment by wiswedel** [comment] 2019-11-01 11:39
duplicate of https://github.com/nextcloud/talk-ios/issues/170

**Closed as completed by wiswedel** 2019-11-01 11:39 UTC

**Comment by lmamane** [comment] 2019-11-04 07:30
Sorry, I missed the other one.
