### ISSUE TITLE
Nextcloud talk mobile client |  after System-update to 14.2 no videochat possible

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/talk-ios#428] opened 2020-11-27 20:32 UTC
iPhone XR | iOS-Version 14.2 

iOsTalk App 10.1.0
24.11.2020

Nextcloud 19.0.5
Nextcloud Talk - "Server" App  9.0.6 (Latest Version)

Before the iPhone was updated to 14.2, the Talk app ran smoothly. Video chat also worked

After system update to 14.2 the app crashed immediately when opening. (see here: https://github.com/nextcloud/talk-ios/issues/425)

Try to solve the problem:
- The app was uninstalled and reinstalled
- Now it could be opened. The text chat worked immediately.
==>  The video chat does not work.

**Comment by SystemKeeper** [comment] 2020-11-28 11:26
> * ==>  The video chat does not work.

Can you give us a few more details about this?

* What does 'does not work' mean? No connection? No video? Any status/error message? etc.
* Do audio calls work?
* Does it matter if you or another person starts the call?
* Is the other person running on iOS as well or on web?
* Are you using internal signaling (default) or do you have an external signaling server (hpb) running?

**Comment by osm-frasch** [comment] 2020-11-28 12:19
- I think the connection is there, because the text chat works

- audio calls do not work either

- No, it does not matter who starts the call. We have tried this

- We have also tried video calls via different systems. From Windows PC to iPhone, from iPhone to Android and vice versa. 
No success! 
We have also tried video calls from Windows PC to Android and we tried Videocalls from Win-PC to Win-PC and Linux. This worked immediately as always 

- We using an external standalone Signaling Server, The status message is set to "OK". The server is running!
In addition we also use STUN and TURN.

**Comment by s1rAleks** [comment] 2020-11-30 14:46
Since my problem is very similar, I am reporting here.
I have been using iOS 14.2 since its release in early November and have successfully conducted several video conferences.
Since last Thursday I have had the problem of not getting sound and picture during conversations with Nextcloud Talk app 10.1.0.
Shortly after discovering, the update 10.1.1 was released in the Apple app store, but no change in the behaviour.

User A on Google Chrome 87.0.4280.67
User B on iPad Pro with iOS app 10.1.1

When a call is started (doesn't matter who starts it) and the other user connects, it only shows his avatar and there is no sound.
On the side of user B the name of the other user is not shown, stating only guest. This applies also on voice calls only.
Text chat functions normally. When both use Google Chrome the call works fine.

I already tried to un- and reinstall the app on iOS, including restarting the device and also resetting the network settings.

Tested with:
iOS 14.2 (iPhone 11 Pro & iPad Pro)
Nextcloud Talk iOS App - 10.1.0 & 10.1.1

Nextcloud Server - 19.0.5 & 20.0.2
Nextcloud Talk Server App - 9.0.6 & 10.0.3

**Comment by Ivansss** [comment] 2020-11-30 14:56
There was a regression introduced in Talk version 10.1. Calls using an external signaling server are not working.
It has been fixed in #432 
Talk iOS 10.1.2 is waiting for review and it will probably be available in the App Store later today or tomorrow.
Sorry for the inconvenience!

**Comment by s1rAleks** [comment] 2020-11-30 23:41
Was able to update Talk iOS to 10.1.2 and it works again. Thank you very much!

**Closed as completed** 2020-12-01 08:27 UTC
Labels: bug

**Comment by osm-frasch** [comment] 2020-12-01 09:11
In my environment i have a user whose update only became effective after he had deleted the app and then reinstalled it. Now the video chat works again. Also thanks a lot
