### ISSUE TITLE
Behaviour for clicking links

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/talk-ios#227] opened 2019-05-16 13:01 UTC
### Current behaviour:
When clicking a link, it opens the `More Menu` with actions like `Open`, `Add to Reading List`, `Copy` and `Share ...`.

![IMG_69F2A4BC0EA5-1](https://user-images.githubusercontent.com/1250540/57855576-416a0d80-77eb-11e9-97e2-0f370f3a98e6.jpeg)

### Proposed better behaviour:
Similar to other apps, a simple click on the link should open the link in Safari. The `More Menu` should only be shown on a long press.

**Comment by Ivansss** [comment] 2019-05-16 13:08
Hi @georgehrke,

It should work as the proposed behavior 🤔 
At least that's how it works in every device I have tested the app with.

**Comment by georgehrke** [comment] 2019-05-16 13:12
Hm, but even if i tap really fast, it opens the `More Menu`.

(I'm using Nextcloud Talk 6.1.0)

**Comment by Ivansss** [comment] 2019-05-16 13:24
You are right, I can reproduce it 😅

**Comment by SystemKeeper** [comment] 2020-11-20 12:13
I'm unable to reproduce this with 10.0.1 on iOS 14, works as described in first post (short touch opens safari, long touch menu). Can anyone confirm? @georgehrke @Ivansss  ?

**Comment by Ivansss** [comment] 2020-11-20 13:44
I think this issue was in some specific iOS 12 version
Closing the issue since I can't reproduce it in iOS 13 or 14.

**Closed as completed by Ivansss** 2020-11-20 13:44 UTC
Labels: enhancement, 1. to develop
