### ISSUE TITLE
Theming changes flow into Nextcloud Talk iOS app

### ISSUE THREAD

**Issue by nctester1x** [nextcloud/talk-ios#355] opened 2020-09-23 14:33 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if theming changes flow into Nextcloud Talk iOS app

**Describe the solution you'd like**
Theming changes flow into Nextcloud Talk iOS app like it does on Nextcloud iOS app

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wiswedel** [comment] 2020-09-30 19:22
Duplicate of https://github.com/nextcloud/talk-ios/issues/360

**Closed as completed by wiswedel** 2020-09-30 19:22 UTC
